### ISSUE TITLE
Different mapper for specific filename

### ISSUE THREAD

**Issue by niciki-niciki** [oleg-shilo/codemap.vscode#101]
My use case is related with LOG files that are so different, but have the same .log extension.
Could it be possible to specify a general mapper for all .log files and dedicated mapper for specific filename.log?

Regards,
Daniel

**Comment by oleg-shilo** [comment]
Sorry, Daniel, 
this scenario is not supported and it would be very hard (even though technically possible) to implement with the current extension design.
 
However, you can use a dedicated mapper find in this mapper check the file extension and then handle the log file one or another way. You can level import and call the generic mapper from the dedicated mapper. Though I never tried that :)

**Comment by niciki-niciki** [comment]
That sounds good :)
We always can use the power of progamming language inside e.g.: mapper_log.js file.
Inside it I can check the filename and use another dedicated mapper just for specific filename that I would like to have.
Sound like a freedome ;)

Thank you for a hint!

**Comment by oleg-shilo** [comment]
> We always can use the power of progamming language...

These are the exact words that I always use to describe my own attitude towards choosing between configuration vs convention (in this case code).

Totally aligned with you
