### ISSUE TITLE
Is it possible to change the Explorer tab icon to something else?

### ISSUE THREAD

**Issue by niciki-niciki** [oleg-shilo/codemap.vscode#103]
Hi,

I have one tab for explorer and next to it a tab with a CodeMap - the icons are just the same.

Is it possible to change the default CodeMap tab icon to something else?

The outline already occupies the class icon, so I propose to use a function icon instead.

Regards,
Daniel

**Comment by oleg-shilo** [comment]
Hi Daniel, 
I am not entirely happy with the icon either.
I am not entirely sold on the function icon as it can be interpreted as "packaging". But probably some tree-like visual will do.

What about this:

![image](https://github.com/user-attachments/assets/9aa3d869-a540-46b5-8bcd-c702e1995a25)
![image](https://github.com/user-attachments/assets/1abe49e9-2dd7-4f8a-8f49-9a13e64e7154)

**Comment by niciki-niciki** [comment]
That is OK for me.
Thank you!

**Comment by oleg-shilo** [comment]
Done. Release v1.26.2
You can update the extension now.

**Comment by niciki-niciki** [comment]
Hi,

Sorry, but I can't see the changed icon in the last version 1.26.2.
Could you check again?

Regards 
Daniel

**Comment by oleg-shilo** [comment]
Is it possible that you did not restart the VSCode instance?
It reloads the extensions on update but does not refresh the tabs without reloading the editor.
![image](https://github.com/user-attachments/assets/758f5d29-6414-4358-9dbd-a064aae568cc)

**Comment by niciki-niciki** [comment]
I did restart VSCode.

Here is what it looks like at my side:
![20240729_155305](https://github.com/user-attachments/assets/fe9a0989-ba62-457f-83de-4d9b3f343d8e)

**Comment by oleg-shilo** [comment]
Actually, your VSCode is somehow misbehaving. It does show the tab and even highlights the tab with the icon. But the icon is from a completely different extension. Not even the old CodeMap icon.

TBH I have no idea what is happening there. I have now 3 PC  with the latest CodeMap installed (1 manually 2 via auto-update) and all three replaced the icon correctly after the VSCode restart

**Comment by oleg-shilo** [comment]
I can only suggest that you create a new empty VSCode profile and install the extension there:

![image](https://github.com/user-attachments/assets/912d7064-6196-44e7-9af8-9b0e6299f785)

This way you will eliminate any possible interference from other extensions.

Then the new icon/tab will appear on the left side tab-bar.

Recently "MD Preview Enhanced" extension stopped working for me. But after stitching a few times between profiles it started miraculously got fixed. It costs you nothing to try. But definitely, VSCode can have some glitches.

Still, if you see a way to reproduce the problem, please share it with me.

**Comment by niciki-niciki** [comment]
Thank you for all the suggestions.
It seems to by my local problem.
Closing this.
Thank you once again 😃

**Comment by niciki-niciki** [comment]
I have found it!
`"codemap.location": "explorer"`

It should be:
`"codemap.location": "codemap"`
