### ISSUE TITLE
Why can't I map jsx matches?

### ISSUE THREAD

**Issue by zhongweijian-svg** [oleg-shilo/codemap.vscode#106]
![Screenshot 2024-11-14 201703](https://github.com/user-attachments/assets/b8aa182d-78a6-40b1-8abc-82d67392022c)
![Screenshot 2024-11-14 201715](https://github.com/user-attachments/assets/17628cef-29b5-4bd5-8227-55344d70af6b)
![Screenshot 2024-11-14 201735](https://github.com/user-attachments/assets/b19a89ea-00f2-47f0-9814-df7264fd13c4)
I did not modify the configuration, but I could not match the corresponding content successfully, why?

**Comment by oleg-shilo** [comment]
Most likely because the reg expression pattern the mapper is using does not find any matches. Mind you, the regex TypeScript mapper is rather a simple approach that may not produce the best result with jsx files (eg ).

You can share your jsx file and I can have a look at it.

**Comment by zhongweijian-svg** [comment]
I give up, what are the free and easy to use file call index class plug-in? I am a beginner in non-English programming and it is difficult for me to understand structures.

**Comment by zhongweijian-svg** [comment]
I give up, what are the free and easy to use file call relationship index type plug-in? I am a beginner in non-English programming and it is difficult for me to understand structures.

**Comment by oleg-shilo** [comment]
Not a problem, I am closing the issue then.
If you ever want to try I am happy to guide you
