### ISSUE TITLE
Are there plans to support java DOM?

### ISSUE THREAD

**Issue by VAllens** [oleg-shilo/codemap.vscode#11]
Are there plans to support `Java` language DOM?
FYI. Thanks.

**Comment by oleg-shilo** [comment]
I have composed a quick parser for Java (attached). Extract it anywhere and add it to the VSCode settings as a mapper for Java syntax:

![image](https://user-images.githubusercontent.com/16729806/56210944-3318bc80-609a-11e9-8d7c-7435ccc99868.png)

This will produce the map for class and class methods:

![image](https://user-images.githubusercontent.com/16729806/56212163-ceab2c80-609c-11e9-8727-74a783d8eb1f.png)

Please note that the attached mapper is a draft and it may take some improvement. Thus if you do anything useful to it you may share it here and I will add it to the next release.

[mapper_java.zip](https://github.com/oleg-shilo/codemap.vscode/files/3085005/mapper_java.zip)

**Comment by VAllens** [comment]
thank you so much !!! :)
