### ISSUE TITLE
Show/Hide level in code map

### ISSUE THREAD

**Issue by MagTun** [oleg-shilo/codemap.vscode#14]
Issue Type: <b>Feature Request</b>

It would be nice if we could filter the level displayed in the code map and only show level 1 or only level 1 and 2.

**Comment by MagTun** [comment]
Just amazing!

**Comment by oleg-shilo** [comment]
And, forgot to mentioned, the level visibility is controlled via `codemap.maxNestingLevel: 3` (default).
