### ISSUE TITLE
Expand All / Collapse All

### ISSUE THREAD

**Issue by egabrum** [oleg-shilo/codemap.vscode#17]
Issue Type: Feature Request

I'd appreciate a Expand All / Collapse All button.

**Comment by oleg-shilo** [comment]
Unfortunately it's complicated. More than it should :)

To my disappointment VSCode TreeView API is very limited and it ha a number of limitations. One of them (expnding/selecting ) even had to be worked around in CodeMap. See "Limitations" section in https://github.com/oleg-shilo/codemap.vscode.  

I don't see how this can be achieved. But please share your thoughts if you do.
