### ISSUE TITLE
Simplify mapping rules for Python

### ISSUE THREAD

**Issue by egabrum** [oleg-shilo/codemap.vscode#18]
I think the default mapping for Python can be improved (no need to show "class" or "def")

Maybe something like:
(although I can't seem to be able to get rid of the first bracket after the class/function name)

```
   "codemap.py": [
      {
         "pattern": "(?<![^\\r\\n\\t\\f\\v .])class (.*?)[(|:]",
         "clear": "class|:|(",
         "prefix": "",
         "role": "class",
         "icon": "class"
      },
      {
         "pattern": "def (.*?)[(|:]",
         "clear": "def|:|(",
         "suffix": "",
         "role": "function",
         "icon": "function"
      }
   ],
```

**Comment by egabrum** [comment]
Works great for me on 1.10.0
There can be false detections if a doc string contains "class" and ":" in the same line, but this should be rare.
Thanks!

**Comment by oleg-shilo** [comment]
Not a problem. Cheers.
