### ISSUE TITLE
pattern with newline

### ISSUE THREAD

**Issue by rlodbrok** [oleg-shilo/codemap.vscode#21]
Is there a possibility to identify functions including newline?

In AHK it is possible a function exists like this:
func01()
{
code
}

The following should not match:
if (matching){
func01()
}

My pattern today is:
"pattern": "^ *(\\w*)[(].*?[)]\\s*{"

**Comment by oleg-shilo** [comment]
I think your problem is matching https://github.com/oleg-shilo/codemap.vscode/issues/20 100%
