### ISSUE TITLE
Codemap doesn't display async function

### ISSUE THREAD

**Issue by Harag9** [oleg-shilo/codemap.vscode#22]
In my Typescript project I have some async function but these don't appear in the codemap window.

async function loadInfo() {....}

**Comment by oleg-shilo** [comment]
Thank you will need to update the TypeScript parser.

**Comment by oleg-shilo** [comment]
Sorry for such a delay.
Done. Released v1.10.1

**Comment by Harag9** [comment]
Excellent! Loving the codemap, keep up the excellent work!
