### ISSUE TITLE
How to specify a codemap .js when using remote ssh

### ISSUE THREAD

**Issue by derekwallace** [oleg-shilo/codemap.vscode#24]
Hi,
Im trying to write a simple codemap .js to parse my custom file.
Im using VSCode remove development.
Im on a Windows machine and im using remote development on a linux box.

In my workspace  .json file i cant find the right syntax for the file to be found
Ive tried loads
      "codemap.ini": ".vscode/codemap.ini.js",
      "codemap.ini": "<LinuxAbsolutepath>/.vscode/codemap.ini.js",
      "codemap.ini": "<WindowsAbsPath>\\codemap.ini.js",

In the developer tools im always seeing errors of this form.
[Extension Host] Error: Cannot find module '.vscode/codemap.ini.js'

Any suggestions?
Thx
derek

**Comment by derekwallace** [comment]
I tried a traditional VSCode local workspace.
Updated the workspace settings as follows and everything worked as expected.
"codemap.ini": "c:\\derek\\codemap_ini.js",

**Comment by derekwallace** [comment]
Eventually got Remote Development working.
Required Abs path to the file on the remote server
      "codemap.ini": "/AbsPath>/codemap_ini.js",

**Comment by oleg-shilo** [comment]
If you are happy with your ini syntax support you can share it and I will include it in the standard plugin package installation.

**Comment by oleg-shilo** [comment]
I think it can be done.
Changing the issue into enhancement.
