### ISSUE TITLE
<Error>No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by itm-platform** [oleg-shilo/codemap.vscode#26]
Hi there.
I get on CODEMAP EXPLORER <Error>No connection could be made because the target machine actively refused it: 127.0.0.1:18002

I opened that port on my firewall, but it had no effect

Any idea of what can be going on?

**Comment by oleg-shilo** [comment]
It means that the syntaxer server (syntaxer.exe) is not running as it should. Why? Hard to say. It's easier to fix it though...

- Close VSCode. 
- Kill any instance of syntaxer.exe.
- Start VSCode.

There is a good chance it's all you need

**Comment by itm-platform** [comment]
Thanks Oleg. That didn't work. There is [no syntaxer.exe running](https://drive.google.com/a/itmplatform.com/file/d/1vH2uvWZb-WMAmcUnMoiZwoDTsS7NpGMa/view?usp=drivesdk) with or without VS Code open.

I have seen a syntaxer.exe in \.vscode\extensions\oleg-shilo.codemap-1.10.2\bin which I tried to execute. I got this:
```
C:\Windows\Microsoft.NET\Framework\v4.0.30319
Probing cscs.exe ...
Probing cscs.exe failed...
```
Any other suggestion?

**Comment by oleg-shilo** [comment]
The syntaxer server is normally started by VSCode (or any other IDE that uses CS-Script engine for Intellisense).

First you need to see that it can be started without VSCode. Run this:
```ps
syntaxer -port:18002 -listen -timeout:60000 cscs_path:C:\Users\<user>\AppData\Roaming\Code\User\cs-script.user\syntaxer\<whatever version you have>\cscs.exe
```
Let's see if you can start the server then will decide what to do next.

**Comment by itm-platform** [comment]
Oh, this worked :) 

```
C:\Users\dpire\AppData\Roaming\Code\User\codemap.user\syntaxer\1.2.1.0>syntaxer -port:18002 -listen -timeout:60000 cscs_path:C:\Users\dpire\AppData\Roaming\Code\User\cs-script.user\syntaxer\1.2.1.0\cscs.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319
Probing cscs.exe ...
Probing cscs.exe failed...
 >> Server (v1.5.1.0) Started (port=18002)
 >> Syntax engine loaded
 >> Waiting for client request...
 >> Accepted client...
 >> Reading request...
 >> Processing client request
```
Now I get my map
![image](https://user-images.githubusercontent.com/48089993/71670648-d7e64180-2d70-11ea-8917-3aa58934a7d6.png)

Any workaround to make it start with VSCode? I already uninstalled/reinstalled 

As a side note,` \AppData\Roaming\Code\User\` doesn't exist, There is this `\AppData\Roaming\Code\User\codemap.user\syntaxer\1.2.1.0 `

![image](https://user-images.githubusercontent.com/48089993/71670794-665ac300-2d71-11ea-8519-a62421f52ba4.png)


I could not make it collapsable/expandable, though. I will keep trying and open a different issue if I can't make it work
Thanks!

**Comment by oleg-shilo** [comment]
- Syntaxer<br>
Great. It means the all components work correctly and it  might be a deployment issue. BTW your syntaxer path is OK. Mine was from the another VSC plugin ("CS-Script"). BTW check if installing "CS-Script" resolves the situation.<br><br>
Anyway, have a look at https://github.com/oleg-shilo/codemap.vscode/blob/master/src/mapper_cs.ts. This is where starting the syntaxer is implemented. May be it will give you a clue. 

- Collapsing<br>
Try and see if the same C# code as below produces the same effect. Basically I expect only classes to be collapsable:
![image](https://user-images.githubusercontent.com/16729806/71691440-8636c900-2dfb-11ea-9a94-984ea83bd9c3.png)

But you will need to ensure that you have `"codemap.textMode": true`. See the https://github.com/oleg-shilo/codemap.vscode#limitations section

**Comment by itm-platform** [comment]
All good. Thanks Oleg!
