### ISSUE TITLE
Codemap generic mapper does not work with UTF-16 encoded files

### ISSUE THREAD

**Issue by TheBloke** [oleg-shilo/codemap.vscode#33]
Hello

I just installed CodeMapper in VSCode 1.44.2 for Windows. 

The extension seems to be working fine for supported languages, eg C#.  But for some reason I am unable to configure the generic mapper to support a custom language.

I have tried following the example from the Wiki, and copied the example "codemap.x" configuration, renaming it "codemap.ws" as I wish to support files with a .ws extension.   However my newly added variable "codemap.ws" is shown in settings.json to be invalid, and Codemap shows nothing when I test it on a sample file.   I then tried copying the example in exactly, using "codemap.x", and it shows the same thing.

Here's a screenshot demonstrating my attempt to use both "codemap.ws" and "codemap.x" : 
![image](https://user-images.githubusercontent.com/784313/80924422-b3cb5900-8d80-11ea-87e0-dd194823c2c6.png)

As you can see, both show as greyed out, and neither work on sample files with .ws or .x extensions.

I noticed on the Codemap extension configuration page that it has specific entries for Md, Ps1, Py and R , and if I try adding a settings.json value such as "codemap.md" or "codemap.ps1", these show as valid.

Apologies if I've done something wrong, or misunderstood something, or misread the Wiki.  I am very new to VSCode.

Thanks in advance, and for creating Codemap, which looks to be exactly what I want - a way to get an outline view for a niche file extension.

PS.  A separate issue, much less important - the Wiki and description talks of "Refreshing on demand via Refresh toolbar button"; I do not have any button in my Codemap bar except "Collapse All" : 
![image](https://user-images.githubusercontent.com/784313/80924661-1a9d4200-8d82-11ea-9da9-63b0d39993bf.png)

**Comment by oleg-shilo** [comment]
The generic mapper may not work for two reasons:
- Invalid setting file
- invalid regex expression

So I always eliminate the first reason by adding the existing MD mapper but for a new file extension. And then opening the MD wile renamed into the extension I want.

So first ensure you are editing the right file and inserting the mapper value in the right place:

![image](https://user-images.githubusercontent.com/16729806/80968938-28bf9100-8e5c-11ea-894e-97e86c6a87ca.png)
 
I suggest you also do it for the MD mapper (i have attached the file).
[settings.zip](https://github.com/oleg-shilo/codemap.vscode/files/4574826/settings.zip)

When you place the file in the `C:\Users\<user_name>\AppData\Roaming\Code\User` folder you can test it by opening any MD file renamed in the `*.ws`:

![image](https://user-images.githubusercontent.com/16729806/80968568-869fa900-8e5b-11ea-8fa9-f93532f01c27.png)
  
When you get it working you can start experimenting with your regex as your infrastructure is already working.
![image](https://user-images.githubusercontent.com/16729806/80969807-86a0a880-8e5d-11ea-9daf-9fddc71c7c7c.png)


========================

And I will have a look at the missing refresh button. Txs

**Comment by oleg-shilo** [comment]
The new issue has been raised: https://github.com/oleg-shilo/codemap.vscode/issues/34

And fixed now.

**Comment by TheBloke** [comment]
Thanks very much for the fast reply, and for fixing issue #34.

OK, so I understand a lot better now.  Firstly, it is expected that "codemap.ws" will show as 'invalid' in settings.json; this is not actually a problem, and was just my confusion.

So the issue I have is that Codemap will for some reason not recognise the files I am trying to work with.

Let me show you an example.

First - I followed your suggestion and copied "codemap.md" settings to "codemap.ws", and then renamed a .md file to .ws.  This worked fine.  Then I edited these settings to add a couple of new, simple regexes, and confirmed this also worked fine in my test file, as shown here:
![image](https://user-images.githubusercontent.com/784313/80975353-e6756000-8e19-11ea-93a5-e1f0279e2932.png)

Here we see:
* In right hand split, settings.json with my config
* In middle split, test file (renamed MD file to .ws, with some test lines added)
* On left, Codemap is recognising # and ## from MD syntax, and 'function' and 'enum' from my test regexes.

This is all great.

But then when I try with a real .ws file, I get nothing:
![image](https://user-images.githubusercontent.com/784313/80975532-1a508580-8e1a-11ea-9960-06717b8c1c48.png)

This file starts out with some enum entries, which should show in Codemap.  But they do not.  So I am thinking there might be some issue with Codemap when working with my real files?   

Could it be because these files are in UTF-16 format?  I don't know if that affects your code, but I do know I had trouble when I was trying to `grep` these files on a Solaris system, due to the unusual file encoding.

![image](https://user-images.githubusercontent.com/784313/80975980-c4301200-8e1a-11ea-8374-e49e6a894064.png)

Below I have attached one of the real files I am trying to work with.  Would you be able to have a look to see whether it works for you, and if not, what the problem might be?  I have uploaded the file in a ZIP (Github would not let me attach the .ws file directly):

[playerTypes.ws.zip](https://github.com/oleg-shilo/codemap.vscode/files/4575183/playerTypes.ws.zip)

And here is the basic config that I am testing with, which should pick out the `enum` and `function` definitions from that file:
```
"codemap.ws": [
        {
            "pattern": "function \\w*",
            "clear": "function",
            "prefix": "",
            "icon": "function"
        },
        {
            "pattern": "enum \\w*",
            "clear": "enum",
            "prefix": "",
            "icon": "function"
        }
    ]
```
Thanks so much again for your time in helping me.

**Comment by TheBloke** [comment]
> Could it be because these files are in UTF-16 format? I don't know if that affects your code, but I do know I had trouble when I was trying to grep these files on a Solaris system, due to the unusual file encoding.

This is the problem!

I just saved one of my .ws files as UTF-8, and immediately Codemap worked with it:
![image](https://user-images.githubusercontent.com/784313/80983700-c4350f80-8e24-11ea-9e91-eb79db499c1d.png)

So, is there any way that Codemap could support UTF-16 LE files?   Unfortunately I have to work with this encoding, as I am writing modifications to existing code, and all the files are UTF-16 LE.

Thanks again.

**Comment by oleg-shilo** [comment]
Can you check this patch before I publish it. It should fix your problem:

[Uploading codemap-1.11.2.vsix.zip…]()

**Comment by TheBloke** [comment]
Thanks very much for making the fix.  I'd be glad to test it.

The ZIP doesn't seem to be downloadable at the moment?  Did it upload OK?  For me it shows like this:

![image](https://user-images.githubusercontent.com/784313/81178137-a8a24400-8f9f-11ea-86b4-3a4550a4827b.png)

**Comment by TheBloke** [comment]
I've grabbed the updated file from the source repo, going to try putting it in place now.  One minute..

**Comment by TheBloke** [comment]
It works!  I now have enums and functions visible on my UTF-16 .ws files.

I got a few errors when I manually compiled mapper_generic.ts to mapper_generic.js, but the resulting .js file still seems to work fine.

So yes, please could you push this to an official release.

Thanks very much for the fast resolution!

**Comment by oleg-shilo** [comment]
Great. Will publish in a min

**Comment by oleg-shilo** [comment]
Done
