### ISSUE TITLE
Not working for Javascript file

### ISSUE THREAD

**Issue by sannamalai176** [oleg-shilo/codemap.vscode#35]
Code map is not showing the methods in javascript file.

**Comment by oleg-shilo** [comment]
Seems like it does.

![image](https://user-images.githubusercontent.com/16729806/81488230-86633b80-92a9-11ea-870e-afce2a4968d4.png)

**Comment by clarkras** [comment]
I have the same problem - the codemap explorer is empty when editing javascript files.
![image](https://user-images.githubusercontent.com/2540950/90301442-b562ed80-de54-11ea-8e7d-f56d3b05a4fb.png)

**Comment by oleg-shilo** [comment]
It would be great if any of you guys can provide some data that can help to reproduce the problem. Like a file content.

The JS parsing for CodeMap is rather very generic as it does not use and industry grade parsers like Roslyn. Thus addressing any parsing problems without and context is close to impossible.

**Comment by oleg-shilo** [comment]
One thing that is obvious from your image is the absence of the keyword `function`. If it is used then parsing works as expected:

![image](https://user-images.githubusercontent.com/16729806/90302869-ab8cc900-deec-11ea-80be-f8902524141f.png)

Though I am a wrong person to comment on JS syntax ambiguities. 

CodeMap is using a TS parser so most likely it will miss some edge cases of valid but less canonical JS syntax. Thus ideally I would like to get the community help here. If someone can contribute a proper JS mapper (either regex based or a dedicated one). I wil gladly incorporate it.
