### ISSUE TITLE
add search or filter?

### ISSUE THREAD

**Issue by zeg** [oleg-shilo/codemap.vscode#36]
it's difficult to find a node in a long list
![SE`1I}XZC7O6{Z5EPH4UDPX](https://user-images.githubusercontent.com/149013/82552377-8fe78000-9b94-11ea-8d9f-cac2e3129762.png)

**Comment by oleg-shilo** [comment]
Done in v1.12.0
* Implemented Quick Pick (Alt+P) for simple search/filter

**Comment by Harag9** [comment]
:) Nice
