### ISSUE TITLE
Custom mapper for multiple file extensions

### ISSUE THREAD

**Issue by adamerose** [oleg-shilo/codemap.vscode#37]
Can I define a [custom mapper](https://github.com/oleg-shilo/codemap.vscode/wiki/Adding-custom-mappers) that applies to all file extensions? Or even better, be able define the file extension it should apply to with regex?

**Comment by oleg-shilo** [comment]
> ...custom mapper that applies to all file extensions...

Not exactly but you can map all extensions you come up with to a single mapper:

```json
"codemap.ext1": "config:codemap.ext",
"codemap.ext2": "config:codemap.ext",
"codemap.ext3": "config:codemap.ext",
"codemap.ext": [
  {
      <your universal mapper>
 }
]
```

> ...the file extension it should apply to with regex?

Not  at the moment. The mapper lookup algorithm is going i n a different direction `extension -> mapper`, not the opposite way.  Thus it will need to be reversed to "mapper -> extension" to allow matching file extensions. Doable but basically the lookup will need to be redesigned. Thus it has to be a good reason ofr that.
