### ISSUE TITLE
Support newline in regex

### ISSUE THREAD

**Issue by adamerose** [oleg-shilo/codemap.vscode#38]
I'm trying to denote code sections like this which requires detecting the section with the top line and naming it with the bottom one

```
# ==============================================================================
# Authentication
```

**Comment by oleg-shilo** [comment]
Since regex based mapper evaluates the code line by line you will need to use a dedicated mapper:
https://github.com/oleg-shilo/codemap.vscode/wiki/Adding-custom-mappers#mapping-with-a-dedicated-mapper

It is actually not as complicated as one might think. :)
