### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by figurcoe** [oleg-shilo/codemap.vscode#43]
It would be great, if the output could be sorted alphabetically, respecting namespaces, classes, ... Could it be a solution, to implement an alternative data structure being returned from the mapper? This way old code would keep on working flawlessly, but a new mapper could return more information about the structure of the code than it is possible righ now?

Opened with reference to #42.

**Comment by oleg-shilo** [comment]
Done. Please update to v1.16.0
The feature is controlled via `codemap.sortingEnabled` setting

**Comment by figurcoe** [comment]
Cool, thanks a lot, I'll give it a shot latest on the weekend... 

Am September 23, 2020 10:33:03 AM UTC schrieb Oleg Shilo <notifications@github.com>:

**Comment by figurcoe** [comment]
Seems to work, thanks. Would you see a possibility to also sort the trees in respect to each other?
