### ISSUE TITLE
Tab indented files show flat tree

### ISSUE THREAD

**Issue by setnone** [oleg-shilo/codemap.vscode#48]
Hi, thanks for the great extension!

I'm trying to make a simple custom mapper for my html files:

```
"codemap.html": [{
    "pattern": "<[a-z][^<>]*(?:(?:[^/]\\s*)|(?:\\s*[^/]))>",
    "icon" : "function"
}]
```

With my files being indented with tabs i get the folowing results: tree stays flat after the first level. 
<img width="400" alt="tabs" src="https://user-images.githubusercontent.com/62870655/94357306-62728c00-00ca-11eb-88d3-52ea12d3164e.png">

When i change indentation to spaces the tree structure is correct:
<img width="400" alt="spaces" src="https://user-images.githubusercontent.com/62870655/94357317-76b68900-00ca-11eb-9731-8894023cec0e.png">

Is there a way to use tabs with proper tree structure?

**Comment by oleg-shilo** [comment]
No there is none. :(

Tree view rendering algorithm does not allow whitespaces. You can cheat by using a non whitespace character that VSCode will not trim. 

![image](https://user-images.githubusercontent.com/16729806/94568758-4597ad80-02b0-11eb-92a1-be4a7ee12975.png)

However I recommend to disable `textmode` :
![image](https://user-images.githubusercontent.com/16729806/94568931-7841a600-02b0-11eb-82d9-aa48763e0862.png)

It was introduced a s a workaround for TreeView defect, which VSCode team now fixed.

Thus if you start using normal TeeView rendering the  indentation will no longer be an issue
