### ISSUE TITLE
codemap.quick_pick not found

### ISSUE THREAD

**Issue by besenwagen** [oleg-shilo/codemap.vscode#51]
Using the quick pick command causes an error, unless the extension has been activated before in the same session by opening the sidebar view. (For myself, the sidebar feels completely redundant, to be honest.)

**Comment by oleg-shilo** [comment]
Indeed it was a mistake in the activation events. Fixed now. 
The fix will be available in the next release. 

> ...the sidebar feels completely redundant, to be honest...

:o)
Well sidebar is what CodeMap is. "Quick pick it was some later addition suggested by one of the users.

**Comment by besenwagen** [comment]
It’s the nightmare of every UX developer to see how people actually use the products they designed 😂
