### ISSUE TITLE
Custom mapper (custom extension) reports "Unknown Configuration Setting"

### ISSUE THREAD

**Issue by faulknermano** [oleg-shilo/codemap.vscode#52]
Hi, I am using a custom mapper for the extension ".ls". This mapper used to work before but when I opened up an .ls file today, I found that the config was greyed out like this ("Unknown Configuration Settings"):

![image](https://user-images.githubusercontent.com/8240149/109419980-2061b500-799e-11eb-8f26-ab0ac9e85efe.png)

I'm on VS Code 1.53.2, and I wondering if this is related to a recent update.

Thank you for reading!

**Comment by oleg-shilo** [comment]
TBH I am not sure what is the logic being config items being grayed out (vsc v1.56.2).
Thus I was just working on Issue #50 and the corresponding entry `codemap.mb` is also grayed out but... it does work.
So not sure what is happening there.
