### ISSUE TITLE
Tree in alphabetical order

### ISSUE THREAD

**Issue by BassLineHUN** [oleg-shilo/codemap.vscode#6]
Hello,

Is it possible to make a function list with alphabetical order?
I am using this nice plugin for a special programing language where
would be easier to search in this alphabetical order rather than presence.

If you have any idea for it please let me know.
Regards,

Joe

**Comment by oleg-shilo** [comment]
It is a rather difficult one. Sorting can only make sense for a flat list functions. However codemap is generated for of classes with sub-classes then alphabetical sorting becomes problematic:

```
classA
   classB
      member10
      member77
   classD
      member1
      member2
classC
   member0
```
