### ISSUE TITLE
[suggest] add a "search select words in code map" to right click menu

### ISSUE THREAD

**Issue by zeg** [oleg-shilo/codemap.vscode#60]
and "search select words in all code map of current project"

**Comment by oleg-shilo** [comment]
You can achieve the same experience already: Ctrl+T and start typing the desired word

**Comment by zeg** [comment]
errr...

vscode cannot recognize dynamically added object properties in javascript ,  so goto/peek definition mostly not working on my project

I have to use codemap to achieve this
