### ISSUE TITLE
regular expression with [

### ISSUE THREAD

**Issue by aleusius81** [oleg-shilo/codemap.vscode#68]
Hi

I'm trying to outline my proprietary file format similar to the INI format. The bracket [ in my regular expression doesn't seem to be recognized. What am I doing wrong?
Expression: "pattern": "\[[a-zA-Z0-9_=]+\] \\w*",

**Comment by oleg-shilo** [comment]
Not sure. You will, need to use one of the online Regex testers to see what is happening there

**Comment by aleusius81** [comment]
Hi. These regex testers show the expected result. 
`"pattern": "[[a-zA-Z0-9_=]+] \w*",`  above was entered in as `"pattern": "\[[a-zA-Z0-9_=]+\] \\w*",`

**Comment by oleg-shilo** [comment]
OK, changing it to defect. 

Please share with me the samples of the signatures you are trying to match

**Comment by oleg-shilo** [comment]
Does this help?
![image](https://user-images.githubusercontent.com/16729806/165765384-779489c4-8ecb-4ddf-b3d5-74d14b3354fb.png)

**Comment by aleusius81** [comment]
looks good, thank you 👍
