### ISSUE TITLE
Missing Parenthesis

### ISSUE THREAD

**Issue by dub-ab** [oleg-shilo/codemap.vscode#71]
I have a missing open parenthesis on the function name using version 1.16.3.  

![v1 16 3_image](https://user-images.githubusercontent.com/29675729/185439197-e4e0fb01-b286-4ea5-a176-13b044bab018.png)(ver 1.16.3)

I believe this is a bug because by down-grading to version 1.16.2, both parenthesis appear following the function name.  

![v1 16 2_image](https://user-images.githubusercontent.com/29675729/185439202-1cba43a6-224a-4e37-8bde-4613784f434a.png)(ver 1.16.2)

I am using: 
VS Code  1.70.2
python 3.10.6 

Have I applied the extension correctly? Would you need anything else to troubleshoot?

**Comment by oleg-shilo** [comment]
Txs
All good, I can reproduce it. Will have a look.

**Comment by oleg-shilo** [comment]
Sorry, I have misinterpreted my environment behavier and I cannot reproduce the problem. Can you please share your py module definition so I can test the default parser.
My attempt has failed:
![image](https://user-images.githubusercontent.com/16729806/185787186-2ba44300-df83-4512-a9a8-388052b28605.png)

**Comment by dub-ab** [comment]
I believe by your request that you would like me to zip and include the affected for you review.  Included below is a main.zip which has the problem in the original post.  
[main.zip](https://github.com/oleg-shilo/codemap.vscode/files/9389803/main.zip)

I started a fresh project to see if there was something spurrious in the large game file and I am still experiencing the issue with the small attached tiles module.  
[tiles.zip](https://github.com/oleg-shilo/codemap.vscode/files/9389800/tiles.zip)

I am very new to all of this so thank you for your assistance.

**Comment by oleg-shilo** [comment]
Thank you, your sample helped.
It was a peculiar problem with the monkey patched `string.replaceAll`. I cannot put my finger on the actual cause. But it is just simpler to avoid monkey patching and opt for the direct call to regex  version of `string.replace`.

If you update the extension it should work now.

**Comment by dub-ab** [comment]
Thank you.
