### ISSUE TITLE
[help]how to use info from line which is after|before the matched line

### ISSUE THREAD

**Issue by iamqiz** [oleg-shilo/codemap.vscode#74]
for example
code is:
```
# the func is used to  xxxxxx
# ggggg
# yyyy
def aaaa(){

}
```
pattern to match func is : ^def\s+.*
i want to show "xxxxxx" from comment line instead of func name "aaaa"
how to do it ?
thanks!

**Comment by oleg-shilo** [comment]
Should be handled the same way as #73
