### ISSUE TITLE
Bug: Exceptions for some classes

### ISSUE THREAD

**Issue by DevSelchow** [oleg-shilo/codemap.vscode#88]
CodeMap Version: 2.1.4.0   (Visual studio [Preview])
Visual Studio Version: 17.7.3
I have two classes where Codemap does not work and is showing exceptions instead:
1. "Object reference not set to an instance of an object."

2. "Value cannot be null.
Parameter name: source"

![Screenshot 2023-08-30 102925](https://github.com/oleg-shilo/codemap.vscode/assets/23420842/e3049920-386b-4eeb-9afa-45f7b2e1f8b3)
![Screenshot 2023-08-30 102943](https://github.com/oleg-shilo/codemap.vscode/assets/23420842/664287dc-a9ce-45c9-a44e-83371fbeab86)

At this time I can sadly not share the classes causing the problem or have ones that reproduce this exceptions. Sorry. 
But their both are rather large C#  WinForms Partial Classes but thats can not be the root cause since other forms work fine.

**Comment by oleg-shilo** [comment]
Please update the extension. It was patched yesterday

**Comment by DevSelchow** [comment]
Indeed that fixed it. Sorry.  Visual Studio did not show me that there was a update available.

**Comment by oleg-shilo** [comment]
Not a problem
