### ISSUE TITLE
Indent deeper than 3 not possible?

### ISSUE THREAD

**Issue by mrcsbmr** [oleg-shilo/codemap.vscode#95]
Hey,

I'm working on a custom mapper for a scripting language. Everything works great so far, except for when I'm trying to implement indents that are deeper than 3 whitespaces. Code Map simply doesn't nest more than 3 indents. 

As you can see in the screenshot, Code Map doesn't show nestings deeper than 3.

![Screenshot 2024-05-28 102732](https://github.com/oleg-shilo/codemap.vscode/assets/40043737/6974bfd1-e176-4d37-841a-d4ba0d89a3df)

Is there any workaround for that? Thanks for your help! :)

**Comment by mrcsbmr** [comment]
Nevermind! I found the Max Nesting Level in the Extension Settings!

**Comment by oleg-shilo** [comment]
Sorry I was not able to guide you sooner.
