### ISSUE TITLE
Make icon as simple additional string

### ISSUE THREAD

**Issue by niciki-niciki** [oleg-shilo/codemap.vscode#98]
Hi, 
I need to say: I love this extension!

Can you make a change to use "icon" as simple, additional string?
That way we could use all emojis that exists already!

Please look at my result with vivado.log:
![CodeMap](https://github.com/oleg-shilo/codemap.vscode/assets/82179307/45a255a6-431e-497c-859f-fc5fdffb7e3d)

To do so, I used icon as "none" and put proper emojis in prefix, based on different regexp matching.
That would be cool to put it in icon instead of prefix.
That way I could fill already empty place for icon in a CodeMap list.

Best regards,
Daniel

**Comment by oleg-shilo** [comment]
Great suggestion Daniel. Thank you.
Will do

**Comment by oleg-shilo** [comment]
Don, in the latest release v2.26.1 you can directly specify emoji as an `icon` field content and it will be injected into the tree node title.
The release has been already published.

**Comment by niciki-niciki** [comment]
I think there is a regression now. Having "none" in icon gives us "none" string instead of an empty icon. It is not compliant with the readme description now.
How to use it now?
Can you provide the updated readme or revert this version?

**Comment by oleg-shilo** [comment]
> I think there is a regression now. Having "none" in "icon" gives us "none" string instead of an empty icon. It is not compliant with the readme description now.

You are right. I have updated wiki and removed mentioning `none` as a special value. Instead one needs to leave the `Icon` field empty.

> "Icon" should be placed in icon region

Unfortunately, it's not possible. Your proposal is about the support of emoji, which is a string and as such it cannot be used instead of the image data:

![image](https://github.com/oleg-shilo/codemap.vscode/assets/16729806/d7c9cf85-f0ee-4bb6-9353-6f040474b60e)
 
This is the VSCode limitation (and not the only one 😄). 
Thus the implementation that can only possibly implement your proposal is conceptually identical to what you did with the prefix field. Diaplaying the emoji text as the first character of the tree node title.

**Comment by niciki-niciki** [comment]
So just stay with icon as it was previously, if we have this VSCode limitation.
Let's just inform people that prefix can be used with emoji inside to have custom icons if needed. You could add my example with vivado.log.
That way the icon will be "clean" again.
What do you think?

**Comment by oleg-shilo** [comment]
> So I would suggest to stay with icon as it was previously,

This is the case already. 
The emoji support was not a replacement for the existing functionality but an extension. The icon field can still contain that image info the same way it was:

![image](https://github.com/oleg-shilo/codemap.vscode/assets/16729806/d3b8fa9d-424c-4dc4-bff1-744de0fe0ca9)

To make it clear I have added the description to the documentation:

![image](https://github.com/oleg-shilo/codemap.vscode/assets/16729806/17ca9291-3076-4fc6-8f1d-627cb38e14bc)

The truth to be told, the emoji character has the same purpose as the icon. So channelling it through the `icon` field is rather natural. This way the dedicated mapper will also push the emoji/icon through the same value `icon` as the generic mapper does.

Though the ideal solution would be to generate SVG from emoji on fly and stick it to the `node.iconPath`.
But... I am not sure it's feasible.
